In [ ]:
import numpy as np

In [ ]:
import time
start_time = time.time()
a = np.matrix('1 2; 3 4')
print(time.time() - start_time)

0.000308990478515625


In [ ]:
a = np.matrix('1 2 4; 3 4 7')
b = np.matrix('8 1 6; 4 6 9')

def soma_matrizes(a,b):
  resp = []
  for linha in range(a.shape[0]):
    l = []
    for coluna in range(a.shape[1]):
      l.append(a[linha,coluna] + b[linha,coluna])
    resp.append(l)
  return np.matrix(resp)

In [ ]:
a = np.random.rand(100, 100)
b = np.random.rand(100, 100)

In [ ]:
inicio_np = time.time()
s = a + b
tempo_np = time.time() - inicio_np

In [ ]:
inicio_nosso = time.time()
s = soma_matrizes(a,b)
tempo_nosso = time.time() - inicio_nosso

In [ ]:
print('tempo np:', tempo_np)
print('tempo nosso:', tempo_nosso)

tempo np: 0.000148773193359375
tempo nosso: 0.013875484466552734


In [ ]:
def teste_soma():
  tempo_final_np = []
  tempo_final_nosso = []
  for i in range(3):
    a = np.random.rand(10**(i+2), 10**(i+2))
    b = np.random.rand(10**(i+2), 10**(i+2))

    inicio_np = time.time()
    s = a + b
    tempo_final_np.append(time.time() - inicio_np)

    inicio_nosso = time.time()
    s = soma_matrizes(a,b)
    tempo_final_nosso.append(time.time() - inicio_nosso)

    del a
    del b

  return tempo_final_np, tempo_final_nosso

In [ ]:
teste_soma()

([6.175041198730469e-05, 0.004966259002685547, 0.3995664119720459],
 [0.019039154052734375, 0.7470543384552002, 68.75058102607727])

In [49]:
import time
import numpy as np
a = np.matrix('1 2; 3 4; 5 6')
b = np.matrix('1 2 3; 4 5 6')

resp = []
for k in range(b.shape[1]): 
  l=[]
  for i in range(a.shape[0]):
    teste = 0 
    for j in range(b.shape[0]):
      teste += b[j,k]*a[i,j] 
    l.append(teste)
  resp.append(l)
print(np.matrix(resp))
    


[[ 9 19 29]
 [12 26 40]
 [15 33 51]]


In [38]:
a = np.matrix('1 2; 3 4; 5 6')
b = np.matrix('1 2 3; 4 5 6')
a*b

matrix([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

In [46]:
import numpy as np
a = np.matrix('1 2; 3 4; 5 6')
b = np.matrix('1 2 3; 4 5 6')

def mult_matrizes(a,b):
  resp = []
  for i in range(a.shape[0]):
    l=[]
    for k in range(b.shape[1]): 
      teste = 0 
      for j in range(b.shape[0]):
        teste += b[j,k]*a[i,j] 
      l.append(teste)
    resp.append(l)
  return np.matrix(resp)

In [54]:
def teste_mult():
  tempo_final_np = []
  tempo_final_nosso = []
  for i in range(3):
    a = np.random.rand(5**(i+1), 5**(i+1))
    b = np.random.rand(5**(i+1), 5**(i+1))

    inicio_np = time.time()
    s = a * b
    tempo_final_np.append(time.time() - inicio_np)

    inicio_nosso = time.time()
    s = mult_matrizes(a,b)
    tempo_final_nosso.append(time.time() - inicio_nosso)

    del a
    del b

  return tempo_final_np, tempo_final_nosso

In [55]:
resultado = teste_mult()
print(resultado)

([1.7404556274414062e-05, 3.528594970703125e-05, 5.888938903808594e-05], [0.00019860267639160156, 0.009972810745239258, 1.2011218070983887])
